name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ashrith2727/ng-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. Login to Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Build Image
      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} ./app

      # 3. Push Image
      - name: Push Image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      # 4. Create kind Cluster Inside Runner
      - name: Create Kind Cluster
        uses: helm/kind-action@v1

      # 5. Deploy Manifests
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f infra/

      # 6. Update Image Version
      - name: Update Deployment Image
        run: |
          kubectl set image deployment/python-app \
          python-app=$IMAGE_NAME:${{ github.sha }}

      # 7. Verify Rollout
      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/python-app
